# An adventure game


from time import sleep

def room1():


    print("")
    print("You're walking in the woods,")
    sleep(2)
    print("There's no-one around and your phone is dead,")
    sleep(2)
    print("Out of the corner of your eye you spot him!")
    sleep(2)
    print("SHIA LABEOUF!")
    sleep(2)
    print("")
    print("What do you do?")
    print("A. Start running")
    print("B. Keep walking")
    answer = input("Answer: ")

    if answer.lower() == "b":
        print("")
        print("He pulls out a knife,")
        sleep(2)
        print("And he stabs you in the back and leaves you there to bleed to death!")
        sleep(2)
        print("")
        print("Game over!")
        print("")
        print("-------------------------------------")
        room1()

    if answer.lower() == "a":
        room2()
        
def room2():

    print("")
    print("He's following you,")
    sleep(2)
    print("About 30 feet back,")
    sleep(2)
    print("He gets down on all fours and breaks into a sprint!")
    sleep(2)
    print("He's gaining on you!")
    sleep(2)
    print("SHIA LABEOUF!")
    sleep(2)
    print("")
    print("What do you do now!")
    print("A. Look for your car")
    print("B. Charge it him")
    answer = input("Answer: ")

    if answer.lower() == "a":
        room3()

    if answer.lower() == "b":
        print("")
        print("He tackles you,")
        sleep(2)
        print("He brandishes a knife and he stabs you,")
        sleep(2)
        print("Over!")
        sleep(2)
        print("And over!")
        sleep(2)
        print("And over, until you can't take it any more!")
        print("")
        print("Game over!")
        print("")
        print("------------------------------------")
        room1()

def room3():

    

    print("")
    print("You're looking for your car,")
    sleep(2)
    print("But you're all turned around,")
    sleep(2)
    print("He's almost upon you now,")
    sleep(2)
    print("And you can see that there's blood on his face,")
    sleep(2)
    print("My god, there's blood everywhere!")
    sleep(2)
    print("")
    print("RUNNING FOR YOUR LIFE,")
    sleep(1)
    print("FROM SHIA LABEOUF!")
    sleep(1)
    print("HE'S BRANDISHING A KNIFE,")
    sleep(1)
    print("IT'S SHIA LABEOUF!")
    sleep(1)
    print("LURKING IN THE SHADOWS,")
    sleep(1)
    print("HOLLYWOOD SUPERSTAR SHIA LABEOUF!")
    sleep(1)
    print("LIVING IN THE WOODS,")
    sleep(1)
    print("SHIA LABEOUF!")
    sleep(1)
    print("KILLING FOR SPORT,")
    sleep(1)
    print("EATING ALL THE BODIES,")
    sleep(1)
    print("ACTUAL, CANNIBAL SHIA LABEOUF!")
    sleep(2)
    print("")
    print("Now it's dark and you seem to have lost him,")
    sleep(2)
    print("But you're hopelessly lost yourself")
    sleep(2)
    print("Stranded with a murderer,")
    sleep(2)
    print("You creep silently through the underbrush,")
    sleep(2)
    print("A-ha! In the distance!")
    sleep(2)
    print("A small cottage with a light on!")
    sleep(2)
    print("Hope!")
    sleep(2)
    print("You move steathily toward it,")
    sleep(2)
    print("But your leg! AH! It's caught in a bear trap!")
    sleep(2)
    print("")
    print("How do you get out of this situation?")
    print("A. Shout for help!")
    print("B. Rip your leg from the bear trap!")
    answer = input("Answer: ")

    if answer.lower() == "b":
        room4()

    if answer.lower() == "a":
        print("")
        sleep(2)
        print("Shia LaBeouf comes running from the cottage,")
        sleep(2)
        print("With an axe in his hand...")
        sleep(2)
        print("He has you now...")
        sleep(2)
        print("")
        print("Game over!")
        print("")
        print("-----------------------------")
        room1()
    
def room4():

    print("")
    sleep(2)
    print("Gnawing off your leg,")
    sleep(2)
    print("(Quiet, quiet)")
    sleep(2)
    print("Limping toward the cottage,")
    sleep(2)
    print("(Quiet, quiet)")
    sleep(2)
    print("Now you're on the doorstep,")
    sleep(2)
    print("Sitting inside, Shia LaBeouf!")
    sleep(2)
    print("Sharpening an axe,")
    sleep(2)
    print("SHIA LABEOUF!")
    sleep(2)
    print("But he doesn't hear you enter,")
    sleep(2)
    print("SHIA LABEOUF!")
    sleep(2)
    print("")
    print("This will be your only chance! How do you take him down?")
    print("A. Charge at him with only your fists!")
    print("B. Sneak up behind him!")
    answer = input("Answer: ")
    if answer.lower() == "b":
        end()

    if answer.lower() == "a":
        print("")
        print("You charge at him,")
        sleep(2)
        print("But he sees you coming,")
        sleep(2)
        print("And he chops off your head!")
        sleep(2)
        print("")
        print("Game over!")
        print("")
        print("--------------------------------")
        room1()

def end():

    print("")
    sleep(1)
    print("You're sneaking up behind him,")
    sleep(1)
    print("Strangling superstar Shia Labeouf!")
    sleep(1)
    print("Fighting for you life with Shia Labeouf!")
    sleep(1)
    print("Wrestling a knife from Shia Labeouf!")
    sleep(1)
    print("Stab it in his kidney!")
    sleep(1)
    print("Safe at last from Shia Labeouf!")
    sleep(1)
    print("")
    print("You limp into the dark woods,")
    sleep(2)
    print("Blood oozing from your stump leg,")
    sleep(2)
    print("But you have won!")
    sleep(2)
    print("You have beaten Shia Labeouf!")


# Leave this at the bottom - it makes room1 run automatically when you
# run your code.
if __name__ == "__main__":
    room1()
